version: '{build}'

image: Visual Studio 2017

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
    - dev
    - master

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - cmd: echo %JAVA_HOME%
  - ps: Get-Command mvn
  - cmd: mvn -v
  - cmd: npm i -g azure-functions-core-tools
  - ps: Get-Command nuget

build_script:  
  - cmd: mvn clean install -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B -U -Dgpg.skip 
  - cmd: mvn archetype:generate -DinteractiveMode=false -DarchetypeGroupId=com.microsoft.azure  -DarchetypeArtifactId=azure-functions-archetype -DgroupId=com.library.test -DartifactId=ci -Dversion=1.0-SNAPSHOT -DappName=e2etest -DappRegion=Westus -DresourceGroup=e2etestrg
  - cmd: cd c:\projects\azure-functions-java-library\ci  
  - cmd: mvn clean package -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B
  - cmd: cd c:\projects\azure-functions-java-library  
  - ps:  Copy-Item c:\projects\azure-functions-java-library\target\azure-functions-java-library" "c:\projects\azure-functions-java-worker\endtoendtests\target\azure-functions\azure-functions-java-endtoendtests\EventHubTriggerAndOutputJSON\function.json"
  
test_script:
  - ps: |
      $response = curl http://localhost:7071/api/HttpTrigger-Java?name=CI
      $success = $response.Content -eq "Hello, CI"
      if (-not $success) { exit 1 } 

on_finish:
  - ps: | 
      Stop-Process -Id $proc.Id -Erroraction Ignore

artifacts:
  - path: 'azure-functions-java-library/target/**.jar'

cache:
  - C:\maven\