version: '{build}'

image: Visual Studio 2017

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
    - dev
    - master

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - cmd: echo %JAVA_HOME%
  - ps: Get-Command mvn  
  
build_script: 
  - ps: '& .\build.ps1' 

artifacts:
  - path: '/azure-functions-java-library/target/**.jar'

cache:
  - C:\maven\