jobs:
  - job: "Build"
    displayName: 'Build java library'

    pool:
      name: 1es-pool-azfunc-public
      image: 1es-windows-2022 
      os: windows

    steps:
    - task: npmAuthenticate@0
      displayName: 'Authenticate npm to CFS'
      inputs:
        workingFile: .npmrc

    - pwsh: |
        Write-Host "Java_HOME: $JAVA_HOME"
        Get-Command mvn
      displayName: 'Check Maven is installed'

    - pwsh: '& .\build.ps1'
      displayName: 'Build project with java library'
      env:
        NPM_CONFIG_USERCONFIG: $(Build.SourcesDirectory)/.npmrc
